apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-generator
  namespace: weather-pipeline
  labels:
    app: weather-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-generator
  template:
    metadata:
      labels:
        app: weather-generator
    spec:
      containers:
        - name: weather-generator
          image: fbivinay/weather-generator:latest
          imagePullPolicy: Always
